---
version: '3'

services:
  drupal:
    environment:
      # The virtual host is used when we want to access our site via an
      # Nginx Proxy locally; and is required by the script
      # ./scripts/https-deploy.sh.
      # See https://blog.dcycle.com/blog/2018-10-27 for details.
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - HASH_SALT=${HASH_SALT}
    ports:
      - "80"
    volumes:
      - "drupal-files:/var/www/html/sites/default/files:rw"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  # Database server
  mysql:
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - "mysql:/var/lib/mysql"

# Specifying the network name makes it predictable on all environments,
# for example when running ./scripts/migrate-all.sh, or when running browser
# tests on a CI environment, or any other tasks which requires external
# docker containers to connect to our network.
# This network (starterkit_drupal8site_default) has been previously created in
# ./scripts/deploy.sh
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: starterkit_drupal8site_default

volumes:
  mysql:
  drupal-files:
